### PR TITLE
Fix bug: no error message shown when deleting exercise in regime with duplicate index

### PR DESCRIPTION
**Pull request by jietung**
I have changed the HashSet in `AddRegimeCommand` to integer because if hash `Index`, need to write `hashCode()` in `Index`.

### CODE REVIEW

**Comment by t-cheepeng** [comment]
What's the reason for not implementing the `hashCode` in `Index`?  You can just have it return the hash of the number

**Comment by jietung** [comment]
Is it like this?
```
public int hashCode() {
    Integer i =  new Integer(zeroBasedIndex);
    return i.hashCode();
}
```

**Comment by t-cheepeng** [comment]
Yes it looks something like that. Did your bug got resolved?

**Comment by jietung** [comment]
Yep

**Pull request merged**
